### ISSUE TITLE
Many TACL builtins and keywords are not highlighted

### ISSUE THREAD

**Issue by Ben-Voris** [knovichikhin/vscode_tal#18]
Not all TACL built-ins are highlighted. For example, `#IF` and `#LOOP` are highlighted but `#PUSH`, `#RETURN` , `#SET`, etc. are not. See your test case at https://github.com/knovichikhin/vscode_tal/blob/master/tests/sample.tacl.

Please highlight all TACL built-in commands and built-in variables. These are output by the TACL `BUILTINS` command.

Also, it be would be helpful if the :UTILS:TACL variables were highlighted. These are output with the TACL command `VTREE :UTILS:TACL`.

The builtins and commands are also listed in "Summary of Commands and Built-In Functions" in the *TACL Reference Manual*. 

If you don't have access to a NonStop system, I'd be happy to provide these lists.

**Comment by knovichikhin** [comment]
Current grammar rule assigns function scope (`entity.name.function.tacl`) to all keywords that start with `#`.

For example, this is what it looks like in default theme Monokai Dimmed.

![image](https://user-images.githubusercontent.com/447868/103585964-1cd81300-4eb2-11eb-95f9-bc856a31eb60.png)

Some special functions, such as `#if` or `#loop` are assigned a different scope (`keyword.control.tacl`).

So, if you don't see them highlighted then it's possible your current theme does not recognize scope `entity.name.function.tacl`. Do you mind checking your theme code? Or if you share your theme I can double check.

As to the second part, it's possible to add them. However, it can be tricky because the tokenizer will not be able to recognize command vs variable vs literal. But most of these should be used as stand alone commands. So, I think the best that can be done is to recognize these commands when are used at the start of a line.

For example:

```
#output Who Framed Roger Rabbit {simple text}
who {should be recognized as a command}
```

**Comment by Ben-Voris** [comment]
My theme was set to "Light (Visual Studio)". I switched to "(Light+) (Visual Studio)" and the highlighting appeared for all built-ins. Thanks for the tip.

As for default commands (e.g. "who"), restricting it to the start of a line (ignoring white space), would work for me. But, I can imagine it might cause grief for others. So, it's worth thinking about it. I'll close this issue for now.

**Comment by knovichikhin** [comment]
I added basic :UTILS:TACL handling.
In the future more specific command handling can be added tailored to the specific commands.
