### ISSUE TITLE
TACL directory character ":" should be considered part of a variable name

### ISSUE THREAD

**Issue by Ben-Voris** [knovichikhin/vscode_tal#20]
Given this:

`#push :a:b`

Double-clicking on `:a:b` does not select the entire name.

Or the more common use:

`#push :c`

Double-clicking on `c` does not select the leading colon.

**Comment by knovichikhin** [comment]
I'm not sure that one is possible or appropriate to select the whole string.

It's not appropriate because those are accessors for directories and I haven't seen accessors being selected on double click in other languages.

But nevertheless, maybe we can make it an option.

But I'm not sure it's possible. It's possible to change "word" definition to include some characters. Such as what is done to ^. But then it's a global setting. It does not know that someone clicks on a directory variable (e.g. a leading colon).

And if we step outside of a simple language extension and go into programmatic features I do not see a trigger for a double click event.
https://code.visualstudio.com/api/language-extensions/programmatic-language-features
https://code.visualstudio.com/api/references/vscode-api

**Comment by Ben-Voris** [comment]
I had forgot that one can set the editor word separators per-language using this syntax:

```jsonc
  "[tacl]": {
    // removed ":" to allow variables like "a:b"
    // The colon is used as a separator for variable directories and for elements of a structure.
    "editor.wordSeparators": "`~!@%&*()-=+[{]}\\|;'\",.<>/?"
  }
```

This solves my problem.

**Comment by knovichikhin** [comment]
Glad that it's an acceptable solution.

I looked again at `editor.wordSeparators` to see if extension can have multiple options for it. For example, to have an option to ignore `:` or not. But no luck. Extension seems to be able to set only the defaults.

https://code.visualstudio.com/api/references/contribution-points#contributes.configurationDefaults
